name = "RapidStellarEvolution"
uuid = "74382c01-1d73-4e8a-a552-b9f83f8ca2f2"
authors = ["Caspar William Bruenech <c.w.bruenech@pm.me> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
